ingress-nginx:
  controller:
    hostPort:
      enabled: true
      ports:
        http: 80
        https: 443

    service:
      type: ClusterIP

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

    nodeSelector:
      ingress-ready: "true"

    ingressClassResource:
      default: true
