credentials:
    apiKey: ENC[AES256_GCM,data:rjQ8H5sd7+H8lW7M1snyw9ukYwjFLEAxLoCWaxMz4cH0eFLeDm0lU35eicBu0Q==,iv:vE2QXRHzy2/mhK4TWreudYlvGPCtwi9ma3prwQNxK4c=,tag:DQ8vK3WJ7jt69fbummuECw==,type:str]
    authToken: ENC[AES256_GCM,data:Dk8XsKmU4hCJN4lL8gqgYdc1LXW0ecf8jG0oI5dMjV1l8LAuD2hNrpx8QJNTOpNGV+IoOhCrpV6VFmEgNjBi0w==,iv:85WdCP4pTe4GhINUwHIrG5XrOcO9nFFzo3/w24lgyo4=,tag:KJbEdE/BAkKR4gm3BqB7OA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgRzZYb3B3ClkzV21teG5B
            SCtFcGV2TFZ2ZXNKWkNsOVZDVHJ5ckU2cnpjRklDN0tHYTNwaGZ3OU1QT1IvazhX
            WitpWG1TbjYKNlhkRFFjRlp2Wkk1VUhYRjk4VUNiUmNLVUE3Rysza1FxRUF1TFNr
            TFVEOUxKcjViRmZrb2o4MzdRSXFBZEEyNgo3cC9HSHRvbU40VXZod0ZhdWgxai8y
            WDhrNnU4ZElCZHJGdEtoaW02cXg1MVN0cmN1VXp1MHAyNFVNd2hSRmM3ClYzdStC
            eXRjcE1pYkdIcXZwSlhiakoxOXRsUG9iQ2RiZ3FPOTFDYmx2bWYxb3V2bTQ4S0pU
            dHhiMjN2UzYvSHcKc0ZVY3FlcTY2QW16UVhNNUpiZkJ6dm9aQUJzQlZlbVUxV3VN
            c3ByOUVKa2EvamJkd1plMUZBSEhlb3hEN3hsRQpnVTh6emFaLy95UUlKeGlycTNz
            VEZOdzRqbzlhQTllaW5uZS80bTUwWEFtN2N6eDlac3U5ZEZTRjJiRUFXa2pHCmdv
            R3dKWmNNb0g2aUt2dW4yUk1uTlhrK0JrUXJtVy90aml6ZXNyNWZqWXNGcEtLU2dF
            SXRoWkUreE00a2dob0EKTS9say85L2tOUWtQOUZraGk3Q0Z4MEJMWUxjemg1NE83
            U2NtU0tTamwxWEF4enlrUEZyMm80ck91dVA0U2lmMgpsek8yQWRCS3lpL21adFI3
            ODNYb2dacDJiSHZQTGpIY3BldUNscnI4bk5SRTl0RGJXSys3ekRMblZBaWEycHR2
            CkVMcDV0amUxZERHM1Jad0MzT0tjN1IxUVQzKzlHd2NJVTF5S2ZlaWNTS2I0THRX
            ajFCaUNOWVNmcy9ZTzRNWGsKWm1qang4MkRjM0dMQmtFS0wyRmpaU2hhWkdzdk8r
            eXoxZDZ6QWNYdFpsSQotLS0gcGVrOU5uSDZndUdMbTIxcW5iQnFoNGR3a0VUTWs4
            RndlbnFZQ0dScGxNYwpzUKvBsVwGWPqR2iYSP+FwJylv0A7s+7GDZMJxnK6ce8/D
            DoC2/Jr3EAGW7A1QO9QUFJJrV+Fn3nTOLq5wBZdo
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8sT1ULJYbK/6yY2e/A+Y2E41FUsP315zP0+pQbsnqItqBSFF+eB09Gd99QBKcKzFXxm0JDqlFCBVspSg8Kff8btz/62USgJMHEvft8UcaYJSwmv5EmrIAbXudkiBC3fTAOmFxObNoJpLjXDwQCCMm4AsEiU7nQPI17abyzLEC3L+gXkl3pp5CzkEiPkotQ7w+Cv3xizPiYuKT//qOLxNdk+IVFeYmdF4mVebyW8O8DFnhrTVW2bkZ1TsNkVVU2NKR7kphfZVXTOwaqmi7S1Cgb7yQ1O432xKueOi5pk+0bmNc0ndHpUe6s1ZGo30apL8TSaaGTXPoKFrMMGKivWH0ZMLUtHu4jwmCILCpc78ltw7UyCb1BQpiFQXw2Rhx6+fdKVUJTJEtE8K/nNNNWmOsXf5e5W9Plm/ixrcl2BPCasbsRA+1mKiIrONURmMczD6JEoZ78UK1NKphpWEt0hrwbk1wZ2wFqGuUNv4IY++/3F4iys9sWi3KuQcbQfPc8f/CIFJAqNUcDJ9nmRK3eD/HFP3+YKy3swTNkkaTzk2hjZ72IbocRhxMsbQ31CQZOIzLespnSDz6R/oHD5QNNflERlvcCYCCLZHcXeGEEBcVIUJdjpwdgiGuBiJ4Z+hMZ978g3+oQuAbYcXwE6G/RZv+31mmZ9XkFke2hN+eh6eDNQ==
    lastmodified: "2026-09-08T12:14:54Z"
    mac: ENC[AES256_GCM,data:tprmFnYppoeTGPoZhDto5rEqoAOaWz8SFY++U0GjvqyIsYvvzrqOSjbe4ua25UamwqJ4J0/rIBYHWO/Tpqw190MPe3LWSTW8aoxa7xSm6iiij5YiLxGfoGsJrbIaJr+tCBPsil6eHpJrW1fn1UxKawdBxuI5IRT4U1joPnc32io=,iv:0smVMvOLhjKlRwgZIts98+WRFEk2X9VjSjzwgJ/tbuQ=,tag:v5Nw119eL7Ak/zzsYHoVgA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
