credentials:
    apiKey: ENC[AES256_GCM,data:R8lF11SbE1Q45/5HqVUbhS3l8Y6mm6+Dd/9oski+BkHeDAzcuN6ntuGmCENfEA==,iv:oUytehhya/4IlwwotpsxgYgXxVW3ik2xKN3X/wW/a/Q=,tag:AGl7BV03ITYRGLH74q4Ghg==,type:str]
sops:
    age:
        - recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8sT1ULJYbK/6yY2e/A+Y2E41FUsP315zP0+pQbsnqItqBSFF+eB09Gd99QBKcKzFXxm0JDqlFCBVspSg8Kff8btz/62USgJMHEvft8UcaYJSwmv5EmrIAbXudkiBC3fTAOmFxObNoJpLjXDwQCCMm4AsEiU7nQPI17abyzLEC3L+gXkl3pp5CzkEiPkotQ7w+Cv3xizPiYuKT//qOLxNdk+IVFeYmdF4mVebyW8O8DFnhrTVW2bkZ1TsNkVVU2NKR7kphfZVXTOwaqmi7S1Cgb7yQ1O432xKueOi5pk+0bmNc0ndHpUe6s1ZGo30apL8TSaaGTXPoKFrMMGKivWH0ZMLUtHu4jwmCILCpc78ltw7UyCb1BQpiFQXw2Rhx6+fdKVUJTJEtE8K/nNNNWmOsXf5e5W9Plm/ixrcl2BPCasbsRA+1mKiIrONURmMczD6JEoZ78UK1NKphpWEt0hrwbk1wZ2wFqGuUNv4IY++/3F4iys9sWi3KuQcbQfPc8f/CIFJAqNUcDJ9nmRK3eD/HFP3+YKy3swTNkkaTzk2hjZ72IbocRhxMsbQ31CQZOIzLespnSDz6R/oHD5QNNflERlvcCYCCLZHcXeGEEBcVIUJdjpwdgiGuBiJ4Z+hMZ978g3+oQuAbYcXwE6G/RZv+31mmZ9XkFke2hN+eh6eDNQ== omega
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgRzZYb3B3Clp5YXd3d1E4
            SHpRRlh5Mm9CZU85Yit1TEtNN3k2WFVkcGI2UkM5L2lYelozc1RrRzJ0b3BHZmF0
            SWx3TUtmOEsKZ01KMWVqZ3I5ZUx5T0hydUtTaEVXWG9sd3JFcUw4UW4xamRxNkRI
            bk56dmFTZGpad1RIaDkxSGtkajUzQmhoOApIR094RTloQUlIT3ZYMFRqS0ZwTzBp
            SmlHWXR1SE9kellpeXgwZTRjSy9FZDlsTDFVVE1rNlVzNXRhcGhVbG5BClNubnNG
            VkIxZ0dzcHdLL3gwTGxxTS83Y3hWZEczaFJSWjNSaTJ6VmNDeVNLWG1pTWt2Mm5a
            THBtVUFoUTM4QnQKa3NRTTFoZUxtK1NxbDMwOFVBaDIxMXFvUGlKNUdRd0lRbzhR
            NHRMT2dKaGRDNkhQZy9oRUlRZjZTbzVqb3RQMApnZFZTR01ISU5qK0lCemE3bk84
            Wjdib2ttU1ZWRTRDd2c4NEU1Y2NkZUtUMXRBcXc1aTF1cWtZdUJtaEtDdk9mCmlZ
            TUZIdjJGMmlON1pxVjBKUHpLeDJtTWNKZjRRYXI5NEI2Rlhqc3VHMHd6RmYyaEo5
            VnlVMStEeTN5Sm1mRFcKRFVad1AwWVg5clJJNGtLb2FHMW9LSlpnU012VFU2SGNp
            dnRxd3FkOXRMTUp1RnYveGJxOHFualM4YkVGVFRjUAo1aFUvTHJCK3BCMGdSLzVi
            SkJDOGoyQU1ENDIwa3UvblY2MVpWeGFNTjBpNkZxUzBpRWdvMmRkMkZJaTExTVZW
            CnZDVFBaVHBWZ2U3TnFvV2k4bXhYNGRSM0hhSEpmUFhMTy9mT0JxUzR1NzdsZzgv
            a2JjWEw5Z0tjUGszMnFiR1AKaHpYMi9CVDl4UFFkUFZKVUNuRlZxOGp6Q1ZTYlpt
            UEVDcEJ4cFNDMUprRQotLS0gZTA1NGxzNFlwZEJ1bWR2NGxiS1dCZ3ZNbVQ2cFFL
            RjVCdWhNS2U2SzEwWQp2UboPwllbO1N3PYTtyslBoatyK26blgl9bu/wtf8DN6fk
            X1euUXrF75yHcVJWt03RnU3oUynO9+GQWA1fgVF9
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T10:09:47Z"
    mac: ENC[AES256_GCM,data:vJB4M2cOcmWi54TrQMMSQqYTXThMcrIGb+8bmO9XPOM7/vh58O2Naed2WmgstVeB/bDIJtg3sRDipAT7k/cr93ASZyv5J6IGfWaiK7b9jpx0XLGJpfOGjBqY0NElRIMLLvMVbTdj4XW/Yfmg2wzRb4BavTyICHeaH5L6HlYIqE0=,iv:vegmROrAWqShio5AA/AbQ/ZE4pIl8k9Q+UbJG2J1eMY=,tag:NzXLKEMGKVOHz5VZYlxPZQ==,type:str]
    encrypted_regex: ^(data|stringData|credentials)$
    version: 3.11.0
