credentials:
    apiKey: ENC[AES256_GCM,data:/4GYf1WBdl6UySiBeXtS9aYlbTbT6KefZc9tPTd1qSYLBQMwfarU+mD1TC1i7g==,iv:UGkCqqrMuuIONkYpRjqyPgMm59bZ1KBAfmVT007Ipdo=,tag:lKeFD0AabHTceMjAVMieZQ==,type:str]
    authToken: ENC[AES256_GCM,data:d9I1YQ7QDidz2Y/aUUPn0CEr+JrZIUrOMDXmVVD/JNxVUtsCPhgaXiVn0EqJflwPqUc4MGYNajPWIEY0jTcAyg==,iv:K/7s8l6//aFH06Tf9AjyPGAkbarQxXET/VdghjVQOs0=,tag:k6Enjdxjh6+QjKI6QDLuwQ==,type:str]
sops:
    age:
        - recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8sT1ULJYbK/6yY2e/A+Y2E41FUsP315zP0+pQbsnqItqBSFF+eB09Gd99QBKcKzFXxm0JDqlFCBVspSg8Kff8btz/62USgJMHEvft8UcaYJSwmv5EmrIAbXudkiBC3fTAOmFxObNoJpLjXDwQCCMm4AsEiU7nQPI17abyzLEC3L+gXkl3pp5CzkEiPkotQ7w+Cv3xizPiYuKT//qOLxNdk+IVFeYmdF4mVebyW8O8DFnhrTVW2bkZ1TsNkVVU2NKR7kphfZVXTOwaqmi7S1Cgb7yQ1O432xKueOi5pk+0bmNc0ndHpUe6s1ZGo30apL8TSaaGTXPoKFrMMGKivWH0ZMLUtHu4jwmCILCpc78ltw7UyCb1BQpiFQXw2Rhx6+fdKVUJTJEtE8K/nNNNWmOsXf5e5W9Plm/ixrcl2BPCasbsRA+1mKiIrONURmMczD6JEoZ78UK1NKphpWEt0hrwbk1wZ2wFqGuUNv4IY++/3F4iys9sWi3KuQcbQfPc8f/CIFJAqNUcDJ9nmRK3eD/HFP3+YKy3swTNkkaTzk2hjZ72IbocRhxMsbQ31CQZOIzLespnSDz6R/oHD5QNNflERlvcCYCCLZHcXeGEEBcVIUJdjpwdgiGuBiJ4Z+hMZ978g3+oQuAbYcXwE6G/RZv+31mmZ9XkFke2hN+eh6eDNQ== omega
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgRzZYb3B3CmZOVGNSeXdo
            ZFVXWVlpd0Exc3BlL0p3UzRnK0FCTHpkM2RMU0lTYVR1K3kzQlQvWGduakdDQms0
            RzdYbUVGRGwKTmp0UFZrZ29mSXdSTFRkZG1hSVJSVnF0RGtlaWVIQnNBNytMb3Zq
            WGpkOW1Md0lCWlJxajUvOWdBbS9wVGNvSAoveWtGMHM1SFV1dVZBYjMyVVJLTENJ
            SjdubkxpcXQ4MW1aMndLcWFHQnEzWUNmb2dxeCs0Y0lhL3lwb2xHbHRMCkFWVlVz
            NWxHWThheE9iaHlSb1g5dlZIdXl5RUdoQUI4eGZxakVZR21pK1Qvd1lHdC9MNHh5
            Vkoyc29GMHJDeWMKMDRpeUJHMXB4Q0RxRlh4N05WUG9nS3BaNVJQS3NlVU5KSmdI
            MVdFaXd2ek5HTmNrb0dTd2t6UTA4em5tbklHbApQVlNwc3JLZkpwM1JQeFdOTGhx
            d3dEMjVoU0VVSG9DUU43SE05dUlCN0RzUythRVBscUpnNG5ZYTVSZDdKSGVZCllo
            WVJac3BmLzdIV3ZjYmhXdllGNmplL2lEWjhWN3Zxc2sxcWRHZ3ZvTW9uT1VrRU14
            elEzd1lsQjY2UFBHQ1YKSHdSUmxxMlQ2dEV2RUROWGtrYmVFRjFIbEt4L1RjeTNq
            UEhmUmYzbURvRlAxOGcvYk5ORXp1Q1FmdFRhSGRNYwpaU2hTT2tVYnU3bWFnTi8z
            Y1FuZmtlcXRLWmpWQkNSUGZpaXBSSEpPR2o3Rzk2RGwxL29BeVBXY3ZsMDE5d1k0
            CmpiK3FtNEJsNmdBWG9HTkd1aW1DcWt1R1NUeXJHMFJkcWhkSzBJWEc3ZCt5WDdJ
            Z1NLKzJJOTBDSXZwSHQyR0gKQzloTmh0Ymdic3JjaGxOSHNUdWlRTnE2SlBQSm56
            Rm8xaEhEbzcvLzA1WQotLS0gZlNJTzdrMjI0QkRFNWpZK2tpSXpsTlM5U01FNW5H
            K2dtUml5ZUFqODhwcwqUi9C5jqpzQty8QTmnn7rkmUhFK6m6ZdmCjQ7aHeQIDiuw
            s9Kk6PZ9crtD6q/eM62UXH0eug8cuHJDvMif4Mhu
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T10:13:44Z"
    mac: ENC[AES256_GCM,data:8hpu3kGvo1knI8yEIUHTJgrugZOVDvs7QW2jjKJOL8ANW95PBIXR/OotgTMbUTVXPkUQafUw21TgcrVFX1K9OqIEBdNDLwY5jalN17suKP3O/yF5Nj8sr3Y6lEjNgUyuw5wllB8RhM3HEV5QenNrePSpIifNlr5F0WMgS7JNm0M=,iv:Zb94I0xcLPJl0i//RwPfvu5kzpgG5NuSZIafOjTYEyA=,tag:TFgeoPR6t7907SwI13TJcg==,type:str]
    encrypted_regex: ^(data|stringData|credentials)$
    version: 3.11.0
