jaeger:
  allInOne:
    enabled: true

  jaeger:
    ingress:
      enabled: false
      ingressClassName: nginx
      hosts:
        - jaeger.localhost
      pathType: Prefix

  provisionDataStore:
    cassandra: false

  storage:
    type: memory

  collector:
    service:
      otlp:
        grpc:
          name: otlp-grpc
          port: 4317
        http:
          name: otlp-http
          port: 4318

istio:
  enabled: true
  host: jaeger.localhost
