apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/omegazyadav/otel-demo.git
    targetRevision: main
    path: argocd-apps/apps
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
