apiVersion: v1
kind: Secret
metadata:
  name: grafana-github-oauth
type: Opaque
stringData:
  client_id: {{ .Values.githubOAuth.clientId | quote }}
  client_secret: {{ .Values.githubOAuth.clientSecret | quote }}
