{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.istio.host }}
  gateways:
    - grafana
  http:
    - route:
        - destination:
            host: grafana.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
{{- end }}
