githubOAuth:
    clientId: ENC[AES256_GCM,data:JvsoaQSlAN+W8kTsUXgW3U29UA8=,iv:wcdfcWprVTpzNcg/YWnSvjBRLNwWYDPoJhuPiXOCinQ=,tag:chnYx9IqvUwGp1kgkHcNPQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:OWrAe9V45kPGjNAIttrfFea3c125w5Sy220tHwop3MnJQV1Sgpgxag==,iv:GRYDULJXqLt54z3OVE6vl0RjUzgUOznqjJKltcOTx0g=,tag:3z5dpboOKuKhhQGeMDvlrQ==,type:str]
sops:
    age:
        - recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8sT1ULJYbK/6yY2e/A+Y2E41FUsP315zP0+pQbsnqItqBSFF+eB09Gd99QBKcKzFXxm0JDqlFCBVspSg8Kff8btz/62USgJMHEvft8UcaYJSwmv5EmrIAbXudkiBC3fTAOmFxObNoJpLjXDwQCCMm4AsEiU7nQPI17abyzLEC3L+gXkl3pp5CzkEiPkotQ7w+Cv3xizPiYuKT//qOLxNdk+IVFeYmdF4mVebyW8O8DFnhrTVW2bkZ1TsNkVVU2NKR7kphfZVXTOwaqmi7S1Cgb7yQ1O432xKueOi5pk+0bmNc0ndHpUe6s1ZGo30apL8TSaaGTXPoKFrMMGKivWH0ZMLUtHu4jwmCILCpc78ltw7UyCb1BQpiFQXw2Rhx6+fdKVUJTJEtE8K/nNNNWmOsXf5e5W9Plm/ixrcl2BPCasbsRA+1mKiIrONURmMczD6JEoZ78UK1NKphpWEt0hrwbk1wZ2wFqGuUNv4IY++/3F4iys9sWi3KuQcbQfPc8f/CIFJAqNUcDJ9nmRK3eD/HFP3+YKy3swTNkkaTzk2hjZ72IbocRhxMsbQ31CQZOIzLespnSDz6R/oHD5QNNflERlvcCYCCLZHcXeGEEBcVIUJdjpwdgiGuBiJ4Z+hMZ978g3+oQuAbYcXwE6G/RZv+31mmZ9XkFke2hN+eh6eDNQ==
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgRzZYb3B3CkNtSk9yRkE4
            eHU5SXQ2aG5ZVUNXS2FBQVFaaVZ5aXlERzZtWmE5SEFGMEtaVlFnVW9JVVFnc1FO
            VGxNMFUxNTgKVUtnZmtXMDExNlEyMThoVGh3NkRsZ3ZKMSt2WUNaaGFIbGlWUVl3
            ZmNQZW40N0w4dzdKVUFmbldWMUM1TTR5SgpGRHFqRDNhM09zT2tWb0phUlpvanl0
            R3lrUndnWGNHSkhLOG9BYm1pM0JuZkdjTzdHYWFZVSsvdGo5Q0xQVXVvCkRFWm9W
            VVVBRmFES2RqMGJiNzlENmlZblpCUFBlWDJsSmM5OUxVaVIwL2tlWTdWSlNwR0ZM
            TnpYZzZRTE9lQjQKeS9BVTFQNlVYb0xqTW5Ub0pVRXU4RUpHNk1UQXZFRjJPVEFN
            YjBBYlRHNGlicmx2Tzl1RngvRGg5d1RLUFJ5VQpXT1M3SVRPeS9RNlY1Yndxeity
            d1RpWXdVK0NpVjNaR2FydmNFWXB0d21sU09UeVFRUUZZU0pxMnhLZnAwcUpTCjNn
            MDNzZU9XSHBDdEtkcFQwZURVKzhNNis0blFBb0o1TzJxUm1rcFIvTklJUzRnU0lx
            NXJzZ2JoNlhqNnRHOXgKVktmSWw2NXlwRTQ4M0l0UWFqMEQ0bUxpYzNUY0t1NG96
            STNLeVFRelZyTnBzMStONDVncXYraTZHbXdxZ2ZqOApYb3RFK0V2SG1pWEovNk12
            UXhZL0R2ZlVEWVZraW5VOHVzUXdtWWZBUWVIamVySHo0M2VUVytVVzIzQ1pFckFE
            CjRKWnc5Y0ZtZ3F0Z0xPL2RHVnErQkNDTDdlOGNVQzBrS3k1cXBveGh5OG8xUHhT
            S2FBS3g3ZUNMYVlabUFMZ2wKaHpoMkRqb0VhOGRSRmMwaU1EVUY3bGE2dEgxcFBv
            UUtrRUg5ZGhxM21RbwotLS0gbzZMdmp1Q3pVbDBWb1I5V3F6dWg1c0ViZmZwSDhu
            S1NnYU94dlFnQzVOYwoHanLxEFWwDntpa7lsX0Wjgti7W49RHgYTnNUBLh8B3IoU
            AfH5zzZAk1KzGpPgJ8EmPH9E3deI8E993piCe+oE
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T02:34:16Z"
    mac: ENC[AES256_GCM,data:sP3XsdSWhQTH9hl80MpxIl8bCmZqBbEDre/q8XDLx+TtMQCsEAtBuMoclWbIfFdAiGJSTgqA2vmxcdAtRIew4HVlAlErxbrF8aoVB/wEcvg6xuws4ibZ2+M6TiebpKXM+K+G8FLTRMVLO/vhTOSDywK3uaxpBAQRHplAcln7Wd8=,iv:P924Uvot9cHZZ6qGTnu6ugtAuNKChBCtZdOerhWUH8M=,tag:Vja1WPIlSOnsqJ64Ccmyfg==,type:str]
    encrypted_regex: .*
    version: 3.11.0
