githubOAuth:
    clientId: ENC[AES256_GCM,data:uFOffhBddyA2DensgfFxQ8Np+3s=,iv:PPCO4d2jWMkhBC+Ce6mT1Nezo+1xRtN3G7fK0gfPWDI=,tag:k1IrvNR5jJkA/FzUY1gtXQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:ppo+Km4wRVOKPLBnUbj+LpJr238uQVCRWeN62q6I2U+Pe3s6vdLodw==,iv:CWmwwkvlYTHfEudN3DF9Qu1HHrD/Kyf/Nw1n3r2Bi4Q=,tag:k74HWkE4SxTeub7xXzU/fA==,type:str]
clickhouseDatasource:
    password: ENC[AES256_GCM,data:bkBaDxUL3JzA104HcJXo2Qy121u84fQtDUb+Tp++noM=,iv:09Gz8WbiqKO65RMtcifpOYOgHu6dEOGwsfThcgeEOjU=,tag:IJVu+AxcpGsn9q2BQoryzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgRzZYb3B3CkN4aUdRWUhS
            aXNXMlFNekdGZy9zWUFiR2JQT1hlMmYvVTBuc0crTHhBOUtOalBSQTIrcXpnakY5
            NGtMMkdJTWsKUllBaXJaTE5PSHdYTXNsM3FFNG10MTJ3TXZ0Q3FhTXFFUTlyRnkv
            MTBzcTBkQjlNL2RJclUzNmUxclZpVytGdQpMbkpwS2hENnpsZ0RwalpvWG5wNml5
            bXh4dklUL3VlVEV2M3RyVG5mNWNIRWdhdklmSVprNXVlWE45Y3k2QVF5CkJSVVd5
            RytyVmxpMExWcGNlSHV6b0xRd2lzWmZza2ZHdU0rN3U1YXVpWC9Dci9Nd0RJV3Ra
            c0NrSjBadkhTbmYKMktNZWw0NWNnM1RhaWhCQi82UkdUV3d6S3VISnIzQVhQeGdy
            ZGJNdHM1OVYyTk52M1dzMGZPSzVZdUZ5VEQ0NAo5enh0RjdUYXBxYmNmRlRGdVJo
            WEJVWTZrenpzWlVONFU5eGtYNEFMS2R6dVBKdDlYd3pyL1E2ei9zRTZKNno5CnJK
            WDFJYXFqSms3eis2MUtZQmdMUnVtT0d1MWpNTTZ5QVpMdTNqZ3RiY3Jyai9jZjlU
            a3VpLy94dXRhYkYvYk0KZlZUd043eDFsUzBMRXBBS0llckFraWxjQVQyT2ZWcHVy
            cHpaRitaaEdtSEtYWWVNbzZqS2d4anNMR1RuTDI4dgpDZmVQUitLcUt3RG1ZUzdW
            dEx5U29ydXcrZDJiL3RkbVFheHhSWklRZllUM1llV0htUzd5TjRvekZraVc0eUxw
            ClE2OGdrUVhpVWFCT0FNOVZXVXZDUEdpNVZEbmNGcFg1MjZ0U3ZERktvcHAwdFgz
            b2ZaYkdsT3VubXdxaXpUQm8KZ3FyVCtDSFpNUFc2OENiNXFMMW15cjNqV0R5blZK
            aFNhR1R6Q2xqUUJSUQotLS0gMnkrTFZnSFR5aFRnMDFPS2pSeGJCNktkOW5VOEt4
            NEZEVGdid0NBYTVrZwoE+5+9ivFc5LmSNH2G7CW1Bz5WlWzE6QRr3Epump8ZBeAj
            X3WxM7gKI4rb2uwonQY64ToKQ2XY1I2wZIKrreNL
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8sT1ULJYbK/6yY2e/A+Y2E41FUsP315zP0+pQbsnqItqBSFF+eB09Gd99QBKcKzFXxm0JDqlFCBVspSg8Kff8btz/62USgJMHEvft8UcaYJSwmv5EmrIAbXudkiBC3fTAOmFxObNoJpLjXDwQCCMm4AsEiU7nQPI17abyzLEC3L+gXkl3pp5CzkEiPkotQ7w+Cv3xizPiYuKT//qOLxNdk+IVFeYmdF4mVebyW8O8DFnhrTVW2bkZ1TsNkVVU2NKR7kphfZVXTOwaqmi7S1Cgb7yQ1O432xKueOi5pk+0bmNc0ndHpUe6s1ZGo30apL8TSaaGTXPoKFrMMGKivWH0ZMLUtHu4jwmCILCpc78ltw7UyCb1BQpiFQXw2Rhx6+fdKVUJTJEtE8K/nNNNWmOsXf5e5W9Plm/ixrcl2BPCasbsRA+1mKiIrONURmMczD6JEoZ78UK1NKphpWEt0hrwbk1wZ2wFqGuUNv4IY++/3F4iys9sWi3KuQcbQfPc8f/CIFJAqNUcDJ9nmRK3eD/HFP3+YKy3swTNkkaTzk2hjZ72IbocRhxMsbQ31CQZOIzLespnSDz6R/oHD5QNNflERlvcCYCCLZHcXeGEEBcVIUJdjpwdgiGuBiJ4Z+hMZ978g3+oQuAbYcXwE6G/RZv+31mmZ9XkFke2hN+eh6eDNQ==
    lastmodified: "2026-09-08T11:31:47Z"
    mac: ENC[AES256_GCM,data:p9HimF+8tXZ/54FLw2Zn8b5cZLtjgZc6LNeR86pN41wUHnLzIAWkcw5433eNrAJRl72ThmPqZWKoiJWcxRDuLTGoqw5FRo7EM7Gs5S28q1cuwTcO6qkXq+VpYUzydoIFIao/lKugbjErIYVpKLN8p6iVW3XDAEDuKXLLmeqLsKk=,iv:K5eXF2b99VrJRGfgBEwItRrzzXxm1dacnceUIPV/4XU=,tag:PjIeYOFs/C3zzZ5DJchuwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
