mcpUser:
    password: ENC[AES256_GCM,data:OtUhX3Mh4HcCxwaMUHgwIysfcY/sN53F/7z9mIjzi1Q=,iv:n7VAgfj+BawXgKkO7w/zpyN04bx1WkGsIc8XcvtPRJE=,tag:p3+CiNJDGQ3D3voToAWYkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgRzZYb3B3CmR3OGJiamMr
            OFZXZFhsTWgwOVk0TVRTb2dyb1FQQ3dienYrUTJtM1cyaEpCSmxNUjBWZDdGSjRH
            ajFJaGJSaWEKTGg1a1RUY2tvZjU1b3d0MmsxTlZ0YW5idDNOMU9ZS3ErWmNuem9w
            b01FajFFZnZmOSs4YVFINTZyVmdzZkFvbQpCUlJkeFFCZVlMbGJYUXdSemVNaE5y
            ODM5TmczMTdPd25ENy9peUV2RUpWcXpHYU10bmcyQnNwdmVJdVlIWDMvCm5sQndH
            Y0w5M3lzaVdXOEdQUTRNRGN3R3U2dTA1WitoSWtTVjZaQ1FoMVRvS28rWW11YzhQ
            N1FITFZ3ZUduYTIKaTAzOU84OHhCOGw5UE9KVDJ1ZWxsZmhWSUhNNXdHaGRtbnNG
            YnVPQ0lxQ2hkd1hTa3FGK0xxa3BPMXBVeXptVApySnFHVUZWMXZtRlNsZnl1Ujcx
            N0k1TEVHckpjUEV1Sk43eDhjNG8wV2h4eGVtUGlrOHl6c25MQk02cjIxYzM4ClN6
            OXBqS2JhR3lQNmlHZm8wRm1xM0VEYjFWdkxRRHdJYWNLWXhPOWNaMElvd2JWcHox
            dnB0Q2J2TzU4VTQxYkcKSEFwcFh5bmRhb3NSMlFHeXAyZFNuNFBuOWM0eTN4Wjk1
            clUvSW9TOXFWOWdpVUU1emNxM24zdEJIcTFvL28rNQpZbXVTN0RxNU9jY1lVZ2NG
            Tm1VTzhld1Q3ZVlsQU12dVVoS1lCUmJ5cW42M0Jrek1wK2tRR01lUCthcHdFOUlL
            ClRWYmxmSnEwblhuQ2dIMjhZbWZERFlIMzZLc0JTdFZCN3cySmtlTnE2TE90Qkpq
            NU1LUzhuWnZmQmxxbEU3UXMKZ1BIakVTZzNnaWVUMkUxL2JuTkc5UzlUcnU2UHYv
            QTBDMmtSM1F3WS96NAotLS0gK2lWdmt1LzNZNDdsYUcyVElPOVpXQTcrQWtqRExh
            R1NidzlHM25JN1JySQqhzmgxMpG4kePBZg1AQPTKG1hbPch04GlcnGVdSBktEGa5
            2Tm0wRtyA0ZhqoWVoFpYuE6aPHNzVQAYWqYS7fKA
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8sT1ULJYbK/6yY2e/A+Y2E41FUsP315zP0+pQbsnqItqBSFF+eB09Gd99QBKcKzFXxm0JDqlFCBVspSg8Kff8btz/62USgJMHEvft8UcaYJSwmv5EmrIAbXudkiBC3fTAOmFxObNoJpLjXDwQCCMm4AsEiU7nQPI17abyzLEC3L+gXkl3pp5CzkEiPkotQ7w+Cv3xizPiYuKT//qOLxNdk+IVFeYmdF4mVebyW8O8DFnhrTVW2bkZ1TsNkVVU2NKR7kphfZVXTOwaqmi7S1Cgb7yQ1O432xKueOi5pk+0bmNc0ndHpUe6s1ZGo30apL8TSaaGTXPoKFrMMGKivWH0ZMLUtHu4jwmCILCpc78ltw7UyCb1BQpiFQXw2Rhx6+fdKVUJTJEtE8K/nNNNWmOsXf5e5W9Plm/ixrcl2BPCasbsRA+1mKiIrONURmMczD6JEoZ78UK1NKphpWEt0hrwbk1wZ2wFqGuUNv4IY++/3F4iys9sWi3KuQcbQfPc8f/CIFJAqNUcDJ9nmRK3eD/HFP3+YKy3swTNkkaTzk2hjZ72IbocRhxMsbQ31CQZOIzLespnSDz6R/oHD5QNNflERlvcCYCCLZHcXeGEEBcVIUJdjpwdgiGuBiJ4Z+hMZ978g3+oQuAbYcXwE6G/RZv+31mmZ9XkFke2hN+eh6eDNQ==
    lastmodified: "2026-09-08T10:04:47Z"
    mac: ENC[AES256_GCM,data:ZsGNwbKHPIdd1Nl5KbJp4IugWWzdI/lVZ2sC/Qo8xcxiiOgmfS+R4+SlPw4qEqfG3WaEX/ArQ/c5X5w2FhX0WFCJSm3rWf/BDqhkbnHTbFOXhVKgjL6fN+BKp5DZJKivOasV9E3LUJ1LA31SDIBn0sfKUpq07V9zUdjk23qoPY8=,iv:+hKYv9HrfLUqwCH0ybnf2E4Rv0k3wackGKWSKvPQ8cs=,tag:8twwCAbyt3IYh/GvP6xxoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
