clickhouse:
    password: ENC[AES256_GCM,data:c4hIwzxHsPUyZG8+nfJTbS6YSvZlmTqlVgo/q29mc5Q=,iv:hpJmG/MG2YYJ6TEgP0nC/dN8RZJvHPccZJME4NnV2RI=,tag:s6Mj08RS5uDnsnaZQ2+oPA==,type:str]
auth:
    token: ENC[AES256_GCM,data:sLFwEyg4X8WsQ5yFEsWbFNgHdEWZDiuwvPlJkBwoO5r+kx8TmGFy9aTRCToj2LfBJfktEa4uPyBxFnwALhrYoA==,iv:zN2SwVEXd/b7U52kM6syeKDPNbDf1xE/+utm5uD+vdI=,tag:9TUN4GN4y4uzyJSXvtEL4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgRzZYb3B3CmRRK0wva0VW
            cDQzaXUxRTcrOWlYazhFMm5BVnEzQzJtSzBTbExLZktnWGJKMTZVaEdXWVVYNXcy
            S2RRQjVvdVoKYjljUG9kMjBlb1dvNlRhcHJDN1lmeHlWNmN1UVpxVzhldmpPMkps
            cHJrM1lSU1U0cjJRRHc4SWo1bkE3eVJ0YQphaXpXcFB5MVZnNzhGOU90OGxDZXNG
            c3hEVEsxZHFSeWRSenRqdmoyN1dDNmV2TXVFMkdRRXk0cmtiWXR5MEZpCmFIN3Ns
            dXdWV2lGZGQ1SDY1RjlkdkdHRmpSanBuN1h2V0RqMDBNM3FGU1hTZ3NoT2NUMzNo
            T1E0OVM5NmJIZGcKQUplcmdKbjVHUUlXVDAzRUxDMFFsd21BaXJGMXVDa1lid1NP
            aDhleW8vQVhDTFMxRWVkMWhNTkpXV0tidSt1bQpKSnRIdWlHRnQrNTRITExPUkZq
            VTRmYW1xc2ptakRMb2FSRVBYVTdpTlNiU3IyZmkxQ0JmUllGR3d4WGM4Y3ZDCkJk
            OHVRSXhLK3E4OXV6bTArRHVaZnd0VzRjelBTbWVvYmU5dkJHSFl2VkpqdkpMUDhm
            RGk4SGp4blhYTnV3dXcKeE82WXRHZGpxc1NpQjdvTG5RQXh3aHpheGRKMXV4Zzk5
            Y1AwcU1uZmFyT3RNTEFCZ2RpKzRwQ1c5Mm04RUxVaAplbTVDMlJyODlONUJrNXZh
            dVhLRjR4SG9NeXJTMmYzblZJbmpyTXc3cEh2WFlFSjdJaEhwRVBBbTM2YzEzakFs
            CnFndXJZNHFaWi8zdU55QURZaWREYS9jRjRQaVZEaTRvMHUzYzBJRHBLMWVMZ28r
            SWlEd011TTZ0YnlsRjI4RmkKVXIrSjZlWGN1MXI5dXhzeWZlLzV5WTQ0SzN5L3A5
            NE9RVDRYUTRFZzVFMAotLS0gdEZLVENWK05lZUJzRGk1NlVybURhS3R3dTJkTmJU
            YmphTEJNbHIrc2tlQQpQlxl/xKw2Uh+3kDIGPY5fvEUhpSZcB2xNxLmdzVRvRGuO
            vCVAP2QAqwxvJxn+VRVicZSoOb6Yht9yONGsXrxA
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8sT1ULJYbK/6yY2e/A+Y2E41FUsP315zP0+pQbsnqItqBSFF+eB09Gd99QBKcKzFXxm0JDqlFCBVspSg8Kff8btz/62USgJMHEvft8UcaYJSwmv5EmrIAbXudkiBC3fTAOmFxObNoJpLjXDwQCCMm4AsEiU7nQPI17abyzLEC3L+gXkl3pp5CzkEiPkotQ7w+Cv3xizPiYuKT//qOLxNdk+IVFeYmdF4mVebyW8O8DFnhrTVW2bkZ1TsNkVVU2NKR7kphfZVXTOwaqmi7S1Cgb7yQ1O432xKueOi5pk+0bmNc0ndHpUe6s1ZGo30apL8TSaaGTXPoKFrMMGKivWH0ZMLUtHu4jwmCILCpc78ltw7UyCb1BQpiFQXw2Rhx6+fdKVUJTJEtE8K/nNNNWmOsXf5e5W9Plm/ixrcl2BPCasbsRA+1mKiIrONURmMczD6JEoZ78UK1NKphpWEt0hrwbk1wZ2wFqGuUNv4IY++/3F4iys9sWi3KuQcbQfPc8f/CIFJAqNUcDJ9nmRK3eD/HFP3+YKy3swTNkkaTzk2hjZ72IbocRhxMsbQ31CQZOIzLespnSDz6R/oHD5QNNflERlvcCYCCLZHcXeGEEBcVIUJdjpwdgiGuBiJ4Z+hMZ978g3+oQuAbYcXwE6G/RZv+31mmZ9XkFke2hN+eh6eDNQ==
    lastmodified: "2026-09-08T10:04:47Z"
    mac: ENC[AES256_GCM,data:1D3h6yOcuvWtouk5Gr1tQRAYid+giFwE76zdySGbnicQVhl282hFp4iLnvTsfyYHiwJvBbtDOjzKDWkzIkX7vB8QiNddSzkO2moKz2IXDO4OQskn+ym93BboeIrGVI73cfFraKxi1UnV+5SXC7+ILEU1lbLLMS+r2yVZ5KZVxP8=,iv:u1ZmzCzh4h/qFKMiMKipE82jo8m+NQCAtvFKkiZt84M=,tag:ZnRZF1UsH937nbmc1GBwUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
