collector:
  mode: daemonset
  fullnameOverride: otel-node

  image:
    repository: otel/opentelemetry-collector-k8s

  presets:
    kubernetesAttributes:
      enabled: true
      extractAllPodLabels: false
      extractAllPodAnnotations: false
    kubeletMetrics:
      enabled: true
    hostMetrics:
      enabled: true
    logsCollection:
      enabled: true
      includeCollectorLogs: false

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  ports:
    otlp:
      enabled: false
    otlp-http:
      enabled: false
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false

  config:
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133

    receivers:
      otlp: null
      kubeletstats:
        insecure_skip_verify: true

    processors:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      batch: {}
      resource:
        attributes:
          - key: environment
            value: dev
            action: insert
          - key: k8s.cluster.name
            value: test-cluster
            action: insert

    exporters:
      otlphttp/prometheus:
        endpoint: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/otlp
        tls:
          insecure: true
      otlphttp/loki:
        endpoint: http://loki-gateway.loki.svc.cluster.local/otlp
        tls:
          insecure: true

    service:
      extensions:
        - health_check
      pipelines:
        traces: null
        metrics:
          receivers:
            - kubeletstats
            - hostmetrics
          processors:
            - memory_limiter
            - k8sattributes
            - resource
            - batch
          exporters:
            - otlphttp/prometheus
        logs:
          receivers:
            - filelog
          processors:
            - memory_limiter
            - k8sattributes
            - resource
            - batch
          exporters:
            - otlphttp/loki
