apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-ruler-rules
  namespace: {{ .Release.Namespace }}
  labels:
    loki_rule: "true"
  annotations:
    k8s-sidecar-target-directory: /rules/fake
data:
  demo-app-rules.yaml: |
{{ .Files.Get "files/demo-app-rules.yaml" | indent 4 }}
  infra-rules.yaml: |
{{ .Files.Get "files/infra-rules.yaml" | indent 4 }}
