apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  clickhouse-password: {{ .Values.clickhouse.password | quote }}
  auth-token: {{ .Values.auth.token | quote }}
