apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  labels:
    tier: otel
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/omegazyadav/otel-demo.git
    targetRevision: main
    path: helm/minio
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
