---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.server.replicas }}
  keeperClusterRef:
    name: {{ .Release.Name }}-keeper
  containerTemplate:
    image:
      repository: {{ .Values.server.image.repository }}
      tag: {{ .Values.server.image.tag | quote }}
    {{- with .Values.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  settings:
    defaultUserPassword:
      passwordType: password
      secret:
        name: {{ .Release.Name }}-secret
        key: default
    enableDatabaseSync: true
    extraUsersConfig:
      users:
        default:
          grants:
            - query: "GRANT ALL ON *.* WITH GRANT OPTION"
        {{ .Values.mcpUser.username }}:
          password_sha256_hex: {{ sha256sum .Values.mcpUser.password | quote }}
          grants:
            - query: "GRANT SELECT ON *.*"
