{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.istio.host }}
  gateways:
    - {{ .Release.Name }}
  http:
    - route:
        - destination:
            host: {{ .Release.Name }}-clickhouse-headless.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8123
{{- end }}
