apiVersion: ENC[AES256_GCM,data:H48=,iv:2sFs51T8rf2jQzM9EtXbzNgzDqNnzngC7qL0r4kn63A=,tag:b68l6YCngMHSY4JhybSLtg==,type:str]
kind: ENC[AES256_GCM,data:MyYJEzun,iv:+uUjBXs8OkreL6tsJ1exokiXt/9RGMa3R1Fp+exIGdM=,tag:Pb65oLvRjtBMllyn3TH6Wg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QGX4nr5A7HrcEHN9MwDWKPUNjPs=,iv:S0Gv9S07qLNcweUwuJwrmx8hSH8titu/2sxBqNOCGtY=,tag:7evuIk2HJXSlPIA4g1EROQ==,type:str]
    namespace: ENC[AES256_GCM,data:gWybcdpOmg==,iv:HaR4bX+9RpjsX9ngz8tByYGFnv2c2CZpdWLTUIHK+2Q=,tag:n1fBWkZ/mOqDKUkmvKHPjQ==,type:str]
type: ENC[AES256_GCM,data:nq+gQrGN,iv:DVuII7HiJ8KyjjdE0SE4VodlyqXFZmnfvrLmJgsx0fs=,tag:qnbHPrjUim5fPQ7tdq0qFw==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:zKR9ZIl7lr0vuvdmg0Y/9fSpT28=,iv:PSQODcwz2vAMAufqmcWI86M7DScso5kSfuMBsWCuSyM=,tag:M9olzMLUiQFtcnaw+C0rew==,type:str]
    client_secret: ENC[AES256_GCM,data:rGpOpXjLnQAAPsHesHqanUqQ8TCdmk+/NlF/9LKRj0j/5FOLdsQQGA==,iv:bw+b8uIGtA2AeEFHPlffwdglDDT5VFIaFatkZVsQzJY=,tag:BOyCIXakQOtcKC0Y6DbGEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1yc2EgRzZYb3B3CkRFRE9qZmE0
            MWMxR1BJQ1R6ZllXbCsydERIQTIzUmx1a21abnMrU3JjN3crYWpqdk5URWF2RFB4
            UkVNc0pSdTMKWFo5Mmh3NWxvdjlFaXRoVFN1TXZhdVJsMEpETHQ4bU01aXFSc0Iw
            SUJMZ1M5ZmdRMDJhUUUzS0xPbldYZnNtZwpPNDJ4WHRoTlB2RnJveERsajUzM1cy
            TkFtNFY3SE1NRyt4QTV0UGhlenRLeWtEbjZBRHJGcUxJVll1YTlPTEl2Cldxa1lJ
            Yi8ycWkzb21lS2tWa3pZM0pveFZJTlcvYUN6cVlSRUhQb25TOUZUazROaWpLYVht
            emlaVXU3OFlnUE8KN1dqSm1uKzFKM1RETlRoRXpPa3BITllCQVhUdjhib0pmRlBy
            WlRkQ3JMK3h3RDYyd1Y5dFhTbDhsMkFLOEJPWgpROGZDYkRWOHN2UTNQa1E2K25R
            cjNkVDgwaTIvMERqZlNiMHFxMHpwK1RRRWd6M0FuTDlNUmorelFQYnpPbXFXCk1L
            QWdoZnVrMzZTSTZWYzB2V0loUjNWK213VTNtT0F2d2l6VTBkeDZleDBJSXJMRkd1
            bVdyaldlY29QUFZ1WGoKbnd6KzFjZ0pkeG4weldXT0hpVEk1dnBMNFhCbmxveUt0
            RFlzMUhocTQ2ek90RmtUU2p6WmR4ZzNub210MkVnQQovSDNPaU42VVFzWEhyZXBE
            ZUI4RTJaM1U3eTlMQUx6S1dyVCtEem5aVWdkRkVJNnNWMFphL0kySDdlRnhXbHFX
            CkR6SmZxOVFpN2xrc1pmR1VrMW9GMlU3aDUrMS9PM05pUXZSQ08yeWt4dTMrSlpG
            TWJUQUtXdk8wUEhVOXVObncKV2p3N3BvbmlxVGo0SGZKeGdNdmFmOXV1LzZLblJa
            WVdTL2Z1QnVwNDRUdwotLS0gTll4SCthakJDKzVSTEZ1YWpYbHdiRmFMUFcxdUt4
            UStFVmljK1d2Um9xQQpHjwXJ6Uv9vT7mfGzqyebRH8MC68OxMW1j5+tZ6tSVWQCx
            otW98cTn0ITq02gFdbk6avKwISSQSrouoyQvg5JI
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8sT1ULJYbK/6yY2e/A+Y2E41FUsP315zP0+pQbsnqItqBSFF+eB09Gd99QBKcKzFXxm0JDqlFCBVspSg8Kff8btz/62USgJMHEvft8UcaYJSwmv5EmrIAbXudkiBC3fTAOmFxObNoJpLjXDwQCCMm4AsEiU7nQPI17abyzLEC3L+gXkl3pp5CzkEiPkotQ7w+Cv3xizPiYuKT//qOLxNdk+IVFeYmdF4mVebyW8O8DFnhrTVW2bkZ1TsNkVVU2NKR7kphfZVXTOwaqmi7S1Cgb7yQ1O432xKueOi5pk+0bmNc0ndHpUe6s1ZGo30apL8TSaaGTXPoKFrMMGKivWH0ZMLUtHu4jwmCILCpc78ltw7UyCb1BQpiFQXw2Rhx6+fdKVUJTJEtE8K/nNNNWmOsXf5e5W9Plm/ixrcl2BPCasbsRA+1mKiIrONURmMczD6JEoZ78UK1NKphpWEt0hrwbk1wZ2wFqGuUNv4IY++/3F4iys9sWi3KuQcbQfPc8f/CIFJAqNUcDJ9nmRK3eD/HFP3+YKy3swTNkkaTzk2hjZ72IbocRhxMsbQ31CQZOIzLespnSDz6R/oHD5QNNflERlvcCYCCLZHcXeGEEBcVIUJdjpwdgiGuBiJ4Z+hMZ978g3+oQuAbYcXwE6G/RZv+31mmZ9XkFke2hN+eh6eDNQ== omega
    lastmodified: "2026-08-02T05:55:54Z"
    mac: ENC[AES256_GCM,data:tmp7B8cFdBTeV4iT9SlhKeXDbSYOuqh+qMPhL1yQMC/fxLfEtRWA6cPKqDguWzxW94y41uTEk0WwNpJnseyL8NoU7QrWAZAaoFxQDiEvqa6yK2DgKcd42kKz/3lgfS8ILNdPDFvpyoPO5tZihCOdcMrWkJztAZf1xK8qGhP6XIw=,iv:Q5ZwZtVeqdr1sZvkyyctES2sEEcX8JuKoHX0ohHohqU=,tag:gQeizA9OfKXo25q3ULlaDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
